### PR TITLE
fix(exit-code): determination logic

### LINKED ISSUE #194: --no-error still outputs errors
This works for me as an npm script:

```
    "efr": "eslint-find-rules --unused ~/.eslintrc -n"
```

This does not work. It outputs errors despite the --no-error flag.

```
    "efr": "eslint-find-rules --unused ~/.eslintrc --noerror"
```

I don't understand why it outputs errors anyway though.

### PR DESCRIPTION
**Pull request by sarbbottam**
## existing logic to determine exit code was not correct.

argv.error is true by default
if --no-error is passed argv.error will be false
if -n was passed it would set argv.error to false

fixes #194 
---

@ljharb @ta2edchimp 

Please excuse me for the plethora of PRs over the weekend. Sorry about it.
Hopefully, this is the last one.

### CODE REVIEW

**Comment by sarbbottam** [comment]
@ta2edchimp @ljharb please review when you get time. This should get merged ASAP.

File: src/bin/find.js [hunk 1]
```diff
@@ -25,12 +25,20 @@ var getRuleURI = require('eslint-rule-documentation')
...
 var specifiedFile = argv._[0]
 
 var ruleFinder = getRuleFinder(specifiedFile, argv.core === false)
 
+var processExitCode
+// argv.error is true by default see line #20
+// if --no-error is passed argv.error will be false
+// if -n was passed it would set argv.error to false
+if (argv.n) {
+  argv.error = false
```
Comment (ljharb) [inline src/bin/find.js]: you may prefer not to mutate `argv` here - ie, `const showError = argv.error && !argv.n;` and then `const processExitCode = argv.u && showError ? 1 : 0;`?

Comment (sarbbottam) [inline src/bin/find.js]: I originally did it in that way, but though for this scope it was not required. But good practice is always good practice. Will update it accordingly.

I named the variable as `errorOut`.

**Comment by sarbbottam** [comment]
Please find the test at https://github.com/sarbbottam/eslint-find-rules/blob/master/test/bin/find.js#L100-L112.
