### PR TITLE
fix(core-rules): updated core rules determination logic

### LINKED ISSUE #132: v3.1.0 claims it has an unused ".eslintrc.yml" rule
I updated eslint to v3.1.0 in https://github.com/ljharb/eslint-config and ran `npm run prepublish` (which runs `eslint-find-rules --unused`, among other things).

It complains about two missing rules: "multiline-ternary" which is a new one added in v3.1.0, and ".eslintrc.yml", which is not a rule at all.

### PR DESCRIPTION
**Pull request by sarbbottam**
Fixes #132

### CODE REVIEW

**Comment by sarbbottam** [comment]
@ta2edchimp @ljharb please have a look?

File: src/lib/rule-finder.js [hunk 1]
```diff
@@ -72,13 +72,17 @@ function _getPluginRules(config) {
 function _getAllAvailableRules(pluginRules) {
   var allRules = fs
     .readdirSync('./node_modules/eslint/lib/rules')
-    .map(function removeJsFromFilename(filename) {
-      return filename.replace(/\.js$/, '')
-    })
+  var filteredAllRules = []
+  allRules.forEach(function filterAllRules(filename) {
+    /* istanbul ignore next */
+    if (filename.substr(-3) === '.js') {
```
Comment (ljharb) [inline src/lib/rule-finder.js]: this should probably use `.slice`, since `.substr` is either nonstandard or deprecated

File: src/lib/rule-finder.js [hunk 2]
```diff
@@ -72,13 +72,17 @@ function _getPluginRules(config) {
 function _getAllAvailableRules(pluginRules) {
   var allRules = fs
     .readdirSync('./node_modules/eslint/lib/rules')
-    .map(function removeJsFromFilename(filename) {
-      return filename.replace(/\.js$/, '')
-    })
+  var filteredAllRules = []
+  allRules.forEach(function filterAllRules(filename) {
+    /* istanbul ignore next */
```
Comment (ljharb) [inline src/lib/rule-finder.js]: If coverage is running on not-the-latest eslint such that this ignore is needed, could the tests do something like `touch ./node_modules/eslint/lib/rules/test.yml` to ensure it's covered?

Comment (sarbbottam) [inline src/lib/rule-finder.js]: since `eslint` is mocked, I have [updated the mock's return value](https://github.com/sarbbottam/eslint-find-rules/pull/133/files#diff-912d04f91de422a081173c41ff31335fR10).

**Comment by sarbbottam** [comment]
@ljharb please have a look. Thanks!

File: src/lib/rule-finder.js [hunk 3]
```diff
@@ -72,13 +72,16 @@ function _getPluginRules(config) {
 function _getAllAvailableRules(pluginRules) {
   var allRules = fs
     .readdirSync('./node_modules/eslint/lib/rules')
-    .map(function removeJsFromFilename(filename) {
-      return filename.replace(/\.js$/, '')
-    })
+  var filteredAllRules = []
+  allRules.forEach(function filterAllRules(filename) {
```
Comment (ljharb) [inline src/lib/rule-finder.js]: this could be a filter + map, but this is fine too :-)

**Comment by ljharb** [comment]
LGTM!

**Comment by ljharb** [comment]
(also worth noting; eslint already has https://github.com/eslint/eslint/issues/6685 open to remove the stray file, but this fix is still good)

File: src/lib/rule-finder.js (hunk 3 above)
Comment (sarbbottam) [inline src/lib/rule-finder.js]: I guess number of iteration will be doubled in filter + map.

Comment (sarbbottam) [inline src/lib/rule-finder.js]: Curious to know why do you think `filter + map` would be better in these kind of scenario?

Comment (ljharb) [inline src/lib/rule-finder.js]: Solely because it's ideologically cleaner/pure/more functional than a forEach + a closure. not a huge deal.
