### PR TITLE
fix(rule-finder): Support scoped packages with dashes

### LINKED ISSUE #303: Scoped plugin error
When using [@typescript-eslint/eslint-plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) I'm getting the error:

```js
Error: Cannot find module 'eslint-plugin-@typescript-eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:68:26
    at Array.forEach (<anonymous>)
    at _getPluginRules (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:66:13)
    at new RuleFinder (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:104:21)
    at module.exports (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/lib/rule-finder.js:151:10)
    at Object.<anonymous> (/Users/chris/github/eslint-config/node_modules/eslint-find-rules/dist/bin/find.js:33:18)
```

### PR DESCRIPTION
**Pull request by chrisblossom**
Use eslint's internal functions to support shorthand eslint plugin naming.

fix #303

### CODE REVIEW

File: src/lib/eslint-naming.js [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+
+/**
+ * Removes the prefix from a fullname.
+ * @param {string} fullname The term which may have the prefix.
+ * @param {string} prefix The prefix to remove.
+ * @returns {string} The term without prefix.
+ */
+function getShorthandName(fullname, prefix) {
+    if (fullname[0] === "@") {
+        let matchResult = new RegExp(`^(@[^/]+)/${prefix}$`, "u").exec(fullname);
```
Comment (ljharb) [inline src/lib/eslint-naming.js]: It’s very dangerous to pass user input into the RegExp constructor; let’s find a way to avoid doing it.

File: src/lib/eslint-naming.js [hunk 2]
```diff
@@ -0,0 +1,108 @@
+/**
+ * This is a direct copy and paste from eslint's github repository
+ *
+ * This will need updating if eslint changes their resolution function
```
Comment (ljharb) [inline src/lib/eslint-naming.js]: How does this change if the user isn’t using eslint 6?

File: src/lib/eslint-naming.js [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+ * Eslint version as of 07/01/2019: 6.0.1
+ *
+ * https://github.com/eslint/eslint/blob/219aecb78bc646d44bad27dc775a9b3d3dc58232/lib/cli-engine/naming.js
```
Comment (ljharb) [inline src/lib/eslint-naming.js]: can this be required directly from eslint, instead of copy-pasted?

Comment (chrisblossom) [reply src/lib/eslint-naming.js]: I tried this method at first, but the file location changes between eslint 3, 4, 5 and 6. And I am unsure if it changes between different versions of those major releases as well. It doesn't look like it is exposed as an external API either.

File: src/lib/eslint-naming.js (hunk 1 above)
Comment (chrisblossom) [reply src/lib/eslint-naming.js]: If this is the case, I think a PR upstream to eslint should be done and copied back here.

File: src/lib/eslint-naming.js (hunk 3 above)
Comment (ljharb) [reply src/lib/eslint-naming.js]: if it’s reachable, it’s part of the api.

It’s fine if we have to do try/catch requires to get at the function - that will ensure we get whatever matches the current version of eslint.

File: src/lib/eslint-naming.js (hunk 2 above)
Comment (chrisblossom) [reply src/lib/eslint-naming.js]: I'm fairly certain all changes are backwards compatible and only fixed bugs. As far as I know, if a change isn't compatible with an old version of eslint, the plugin wouldn't be compatible either.

File: src/lib/eslint-naming.js (hunk 1 above)
Comment (ljharb) [reply src/lib/eslint-naming.js]: it’s likely that eslint always uses this with hardcoded prefix values tho.

Comment (chrisblossom) [reply src/lib/eslint-naming.js]: I hard-coded the prefix here: https://github.com/sarbbottam/eslint-find-rules/pull/305/commits/917b078a06f4b9d683209512ef44b0825e1baaa6#diff-aadfa63871a8b6e9a696c0d305e30ffdR35

Is that what you mean?

File: src/lib/eslint-naming.js (hunk 3 above)
Comment (chrisblossom) [reply src/lib/eslint-naming.js]: How would you suggest handling eslint changing/moving file names between eslint minor releases? This plugin could break/work unexpectedly without warning.

File: src/lib/eslint-naming.js (hunk 1 above)
Comment (ljharb) [reply src/lib/eslint-naming.js]: ah yes, fair enough :-)

File: src/lib/eslint-naming.js (hunk 3 above)
Comment (ljharb) [reply src/lib/eslint-naming.js]: try/catch around require for each possible filename. It’s fine if eslint breaks us unexpectedly, that’d be a bug in a non-major.

Comment (chrisblossom) [reply src/lib/eslint-naming.js]: It doesn't look like [eslint v3 exports the functions](https://github.com/eslint/eslint/blob/3.x/lib/config/plugins.js) that we need here. What would you prefer I do? Copy the needed code or setup a fallback naming function? Or maybe it is time to drop eslint 3 support?

Honestly I still think copying the file is the best option as it works with all versions of eslint.

Comment (ljharb) [reply src/lib/eslint-naming.js]: Every function in that file is exported?

Comment (chrisblossom) [reply src/lib/eslint-naming.js]: The load function puts together the long and short names we need here. It doesn't return them, but instead directly requires the plugin here.

https://github.com/eslint/eslint/blob/3.x/lib/config/plugins.js#L109-L129

Comment (ljharb) [reply src/lib/eslint-naming.js]: it’s fine if for some versions of eslint we have to copypaste some of the code, but we should be maximally importing

Comment (chrisblossom) [reply src/lib/eslint-naming.js]: I force pushed (to keep PR commits clean, let me know if this isn't wanted in the future) an update. Let me know what you think

File: src/lib/rule-finder.js [hunk 4]
```diff
@@ -30,32 +30,116 @@ function _getCurrentNamesRules(config) {
   return Object.keys(config.rules);
 }
 
-function _normalizePluginName(name) {
-  const scopedRegex = /(@[^/]+)(\/(.+))?/;
-  const match = scopedRegex.exec(name);
+let eslintNaming;
+// ignore function from coverage because it varies per eslint version
```
Comment (chrisblossom) [inline src/lib/rule-finder.js]: If I need to update this for proper code coverage please advise how to do so.

File: src/lib/eslint-naming.js (hunk 3 above)
Comment (ljharb) [reply src/lib/eslint-naming.js]: Always preferred. Thanks, will take a look.

File: src/lib/rule-finder.js (hunk 4 above)
Comment (ljharb) [reply src/lib/rule-finder.js]: We could move it to a separate file, and istanbul ignore that file?

Comment (chrisblossom) [reply src/lib/rule-finder.js]: I actually just did this and was about to push.

Comment (chrisblossom) [reply src/lib/rule-finder.js]: Done!

**Comment by chrisblossom** [comment]
Are there any other requested changes to get this PR moving along?

**Comment by ljharb** [comment]
@chrisblossom I'm afraid that now that this is rebased on top of eslint 6 support, the eslint 6 tests are failing.

**Comment by chrisblossom** [comment]
> I'm afraid that now that this is rebased on top of eslint 6 support, the eslint 6 tests are failing.

I’ll look into this as soon.

**Comment by chrisblossom** [comment]
Looks like one of the issues is that eslint moved the naming file in `6.1.0`.

v6.1.0: [lib/shared/naming.js](https://github.com/eslint/eslint/blob/v6.1.0/lib/shared/naming.js)
v6.0.1: [lib/cli-engine/naming.js](https://github.com/eslint/eslint/blob/v6.0.1/lib/cli-engine/naming.js)

**Comment by ljharb** [comment]
Sigh. Let’s do another try/catch require on that then.

**Comment by chrisblossom** [comment]
Tests should pass now. Also [increased the mocha timeout in `test/lib/rule-finder.js`](https://github.com/sarbbottam/eslint-find-rules/pull/305/commits/d080cf2503d95186a2c9394d0b2384fcad26ebfd) because tests would randomly fail.

```js
...
    ✓ no specifiedFile - all available rules including deprecated
    1) specifiedFile (relative path) - unused rules
    ✓ specifiedFile (relative path) - unused rules including deprecated (1756ms)
    ✓ specifiedFile (relative path) - current rules (1697ms)
    ✓ specifiedFile (relative path) - current rule config (1722ms)
    ✓ specifiedFile (relative path) - plugin rules (1717ms)

...

  64 passing (39s)
  1 failing

  1) rule-finder specifiedFile (relative path) - unused rules:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at processImmediate (internal/timers.js:439:21)
```

**Comment by chrisblossom** [comment]
Who else needs to review this PR to get it merged and released? I'd like to be able to start using this with my typescript eslint config.
